// <auto-generated>
//   See https://protogen.marcgravell.com/
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: sentencepiece_model.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Lokad.Tokenizers.Vocab
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TrainerSpec : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"input")]
        public global::System.Collections.Generic.List<string> Inputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(7, Name = @"input_format")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InputFormat
        {
            get => __pbn__InputFormat ?? "";
            set => __pbn__InputFormat = value;
        }
        public bool ShouldSerializeInputFormat() => __pbn__InputFormat != null;
        public void ResetInputFormat() => __pbn__InputFormat = null;
        private string __pbn__InputFormat;

        [global::ProtoBuf.ProtoMember(2, Name = @"model_prefix")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ModelPrefix
        {
            get => __pbn__ModelPrefix ?? "";
            set => __pbn__ModelPrefix = value;
        }
        public bool ShouldSerializeModelPrefix() => __pbn__ModelPrefix != null;
        public void ResetModelPrefix() => __pbn__ModelPrefix = null;
        private string __pbn__ModelPrefix;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(ModelType.Unigram)]
        public ModelType model_type
        {
            get => __pbn__model_type ?? ModelType.Unigram;
            set => __pbn__model_type = value;
        }
        public bool ShouldSerializemodel_type() => __pbn__model_type != null;
        public void Resetmodel_type() => __pbn__model_type = null;
        private ModelType? __pbn__model_type;

        [global::ProtoBuf.ProtoMember(4, Name = @"vocab_size")]
        [global::System.ComponentModel.DefaultValue(8000)]
        public int VocabSize
        {
            get => __pbn__VocabSize ?? 8000;
            set => __pbn__VocabSize = value;
        }
        public bool ShouldSerializeVocabSize() => __pbn__VocabSize != null;
        public void ResetVocabSize() => __pbn__VocabSize = null;
        private int? __pbn__VocabSize;

        [global::ProtoBuf.ProtoMember(5, Name = @"accept_language")]
        public global::System.Collections.Generic.List<string> AcceptLanguages { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(6, Name = @"self_test_sample_size")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int SelfTestSampleSize
        {
            get => __pbn__SelfTestSampleSize ?? 0;
            set => __pbn__SelfTestSampleSize = value;
        }
        public bool ShouldSerializeSelfTestSampleSize() => __pbn__SelfTestSampleSize != null;
        public void ResetSelfTestSampleSize() => __pbn__SelfTestSampleSize = null;
        private int? __pbn__SelfTestSampleSize;

        [global::ProtoBuf.ProtoMember(10, Name = @"character_coverage")]
        [global::System.ComponentModel.DefaultValue(0.9995f)]
        public float CharacterCoverage
        {
            get => __pbn__CharacterCoverage ?? 0.9995f;
            set => __pbn__CharacterCoverage = value;
        }
        public bool ShouldSerializeCharacterCoverage() => __pbn__CharacterCoverage != null;
        public void ResetCharacterCoverage() => __pbn__CharacterCoverage = null;
        private float? __pbn__CharacterCoverage;

        [global::ProtoBuf.ProtoMember(11, Name = @"input_sentence_size")]
        [global::System.ComponentModel.DefaultValue(typeof(ulong), "0")]
        public ulong InputSentenceSize
        {
            get => __pbn__InputSentenceSize ?? 0ul;
            set => __pbn__InputSentenceSize = value;
        }
        public bool ShouldSerializeInputSentenceSize() => __pbn__InputSentenceSize != null;
        public void ResetInputSentenceSize() => __pbn__InputSentenceSize = null;
        private ulong? __pbn__InputSentenceSize;

        [global::ProtoBuf.ProtoMember(19, Name = @"shuffle_input_sentence")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool ShuffleInputSentence
        {
            get => __pbn__ShuffleInputSentence ?? true;
            set => __pbn__ShuffleInputSentence = value;
        }
        public bool ShouldSerializeShuffleInputSentence() => __pbn__ShuffleInputSentence != null;
        public void ResetShuffleInputSentence() => __pbn__ShuffleInputSentence = null;
        private bool? __pbn__ShuffleInputSentence;

        [global::ProtoBuf.ProtoMember(12, Name = @"mining_sentence_size")]
        [global::System.Obsolete]
        public int MiningSentenceSize
        {
            get => __pbn__MiningSentenceSize.GetValueOrDefault();
            set => __pbn__MiningSentenceSize = value;
        }
        public bool ShouldSerializeMiningSentenceSize() => __pbn__MiningSentenceSize != null;
        public void ResetMiningSentenceSize() => __pbn__MiningSentenceSize = null;
        private int? __pbn__MiningSentenceSize;

        [global::ProtoBuf.ProtoMember(13, Name = @"training_sentence_size")]
        [global::System.Obsolete]
        public int TrainingSentenceSize
        {
            get => __pbn__TrainingSentenceSize.GetValueOrDefault();
            set => __pbn__TrainingSentenceSize = value;
        }
        public bool ShouldSerializeTrainingSentenceSize() => __pbn__TrainingSentenceSize != null;
        public void ResetTrainingSentenceSize() => __pbn__TrainingSentenceSize = null;
        private int? __pbn__TrainingSentenceSize;

        [global::ProtoBuf.ProtoMember(14, Name = @"seed_sentencepiece_size")]
        [global::System.ComponentModel.DefaultValue(1000000)]
        public int SeedSentencepieceSize
        {
            get => __pbn__SeedSentencepieceSize ?? 1000000;
            set => __pbn__SeedSentencepieceSize = value;
        }
        public bool ShouldSerializeSeedSentencepieceSize() => __pbn__SeedSentencepieceSize != null;
        public void ResetSeedSentencepieceSize() => __pbn__SeedSentencepieceSize = null;
        private int? __pbn__SeedSentencepieceSize;

        [global::ProtoBuf.ProtoMember(15, Name = @"shrinking_factor")]
        [global::System.ComponentModel.DefaultValue(0.75f)]
        public float ShrinkingFactor
        {
            get => __pbn__ShrinkingFactor ?? 0.75f;
            set => __pbn__ShrinkingFactor = value;
        }
        public bool ShouldSerializeShrinkingFactor() => __pbn__ShrinkingFactor != null;
        public void ResetShrinkingFactor() => __pbn__ShrinkingFactor = null;
        private float? __pbn__ShrinkingFactor;

        [global::ProtoBuf.ProtoMember(18, Name = @"max_sentence_length")]
        [global::System.ComponentModel.DefaultValue(4192)]
        public int MaxSentenceLength
        {
            get => __pbn__MaxSentenceLength ?? 4192;
            set => __pbn__MaxSentenceLength = value;
        }
        public bool ShouldSerializeMaxSentenceLength() => __pbn__MaxSentenceLength != null;
        public void ResetMaxSentenceLength() => __pbn__MaxSentenceLength = null;
        private int? __pbn__MaxSentenceLength;

        [global::ProtoBuf.ProtoMember(16, Name = @"num_threads")]
        [global::System.ComponentModel.DefaultValue(16)]
        public int NumThreads
        {
            get => __pbn__NumThreads ?? 16;
            set => __pbn__NumThreads = value;
        }
        public bool ShouldSerializeNumThreads() => __pbn__NumThreads != null;
        public void ResetNumThreads() => __pbn__NumThreads = null;
        private int? __pbn__NumThreads;

        [global::ProtoBuf.ProtoMember(17, Name = @"num_sub_iterations")]
        [global::System.ComponentModel.DefaultValue(2)]
        public int NumSubIterations
        {
            get => __pbn__NumSubIterations ?? 2;
            set => __pbn__NumSubIterations = value;
        }
        public bool ShouldSerializeNumSubIterations() => __pbn__NumSubIterations != null;
        public void ResetNumSubIterations() => __pbn__NumSubIterations = null;
        private int? __pbn__NumSubIterations;

        [global::ProtoBuf.ProtoMember(20, Name = @"max_sentencepiece_length")]
        [global::System.ComponentModel.DefaultValue(16)]
        public int MaxSentencepieceLength
        {
            get => __pbn__MaxSentencepieceLength ?? 16;
            set => __pbn__MaxSentencepieceLength = value;
        }
        public bool ShouldSerializeMaxSentencepieceLength() => __pbn__MaxSentencepieceLength != null;
        public void ResetMaxSentencepieceLength() => __pbn__MaxSentencepieceLength = null;
        private int? __pbn__MaxSentencepieceLength;

        [global::ProtoBuf.ProtoMember(21, Name = @"split_by_unicode_script")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool SplitByUnicodeScript
        {
            get => __pbn__SplitByUnicodeScript ?? true;
            set => __pbn__SplitByUnicodeScript = value;
        }
        public bool ShouldSerializeSplitByUnicodeScript() => __pbn__SplitByUnicodeScript != null;
        public void ResetSplitByUnicodeScript() => __pbn__SplitByUnicodeScript = null;
        private bool? __pbn__SplitByUnicodeScript;

        [global::ProtoBuf.ProtoMember(23, Name = @"split_by_number")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool SplitByNumber
        {
            get => __pbn__SplitByNumber ?? true;
            set => __pbn__SplitByNumber = value;
        }
        public bool ShouldSerializeSplitByNumber() => __pbn__SplitByNumber != null;
        public void ResetSplitByNumber() => __pbn__SplitByNumber = null;
        private bool? __pbn__SplitByNumber;

        [global::ProtoBuf.ProtoMember(22, Name = @"split_by_whitespace")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool SplitByWhitespace
        {
            get => __pbn__SplitByWhitespace ?? true;
            set => __pbn__SplitByWhitespace = value;
        }
        public bool ShouldSerializeSplitByWhitespace() => __pbn__SplitByWhitespace != null;
        public void ResetSplitByWhitespace() => __pbn__SplitByWhitespace = null;
        private bool? __pbn__SplitByWhitespace;

        [global::ProtoBuf.ProtoMember(24, Name = @"treat_whitespace_as_suffix")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool TreatWhitespaceAsSuffix
        {
            get => __pbn__TreatWhitespaceAsSuffix ?? false;
            set => __pbn__TreatWhitespaceAsSuffix = value;
        }
        public bool ShouldSerializeTreatWhitespaceAsSuffix() => __pbn__TreatWhitespaceAsSuffix != null;
        public void ResetTreatWhitespaceAsSuffix() => __pbn__TreatWhitespaceAsSuffix = null;
        private bool? __pbn__TreatWhitespaceAsSuffix;

        [global::ProtoBuf.ProtoMember(25, Name = @"split_digits")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool SplitDigits
        {
            get => __pbn__SplitDigits ?? false;
            set => __pbn__SplitDigits = value;
        }
        public bool ShouldSerializeSplitDigits() => __pbn__SplitDigits != null;
        public void ResetSplitDigits() => __pbn__SplitDigits = null;
        private bool? __pbn__SplitDigits;

        [global::ProtoBuf.ProtoMember(30, Name = @"control_symbols")]
        public global::System.Collections.Generic.List<string> ControlSymbols { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(31, Name = @"user_defined_symbols")]
        public global::System.Collections.Generic.List<string> UserDefinedSymbols { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(36, Name = @"required_chars")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequiredChars
        {
            get => __pbn__RequiredChars ?? "";
            set => __pbn__RequiredChars = value;
        }
        public bool ShouldSerializeRequiredChars() => __pbn__RequiredChars != null;
        public void ResetRequiredChars() => __pbn__RequiredChars = null;
        private string __pbn__RequiredChars;

        [global::ProtoBuf.ProtoMember(35, Name = @"byte_fallback")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool ByteFallback
        {
            get => __pbn__ByteFallback ?? false;
            set => __pbn__ByteFallback = value;
        }
        public bool ShouldSerializeByteFallback() => __pbn__ByteFallback != null;
        public void ResetByteFallback() => __pbn__ByteFallback = null;
        private bool? __pbn__ByteFallback;

        [global::ProtoBuf.ProtoMember(32, Name = @"vocabulary_output_piece_score")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool VocabularyOutputPieceScore
        {
            get => __pbn__VocabularyOutputPieceScore ?? true;
            set => __pbn__VocabularyOutputPieceScore = value;
        }
        public bool ShouldSerializeVocabularyOutputPieceScore() => __pbn__VocabularyOutputPieceScore != null;
        public void ResetVocabularyOutputPieceScore() => __pbn__VocabularyOutputPieceScore = null;
        private bool? __pbn__VocabularyOutputPieceScore;

        [global::ProtoBuf.ProtoMember(33, Name = @"hard_vocab_limit")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool HardVocabLimit
        {
            get => __pbn__HardVocabLimit ?? true;
            set => __pbn__HardVocabLimit = value;
        }
        public bool ShouldSerializeHardVocabLimit() => __pbn__HardVocabLimit != null;
        public void ResetHardVocabLimit() => __pbn__HardVocabLimit = null;
        private bool? __pbn__HardVocabLimit;

        [global::ProtoBuf.ProtoMember(34, Name = @"use_all_vocab")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool UseAllVocab
        {
            get => __pbn__UseAllVocab ?? false;
            set => __pbn__UseAllVocab = value;
        }
        public bool ShouldSerializeUseAllVocab() => __pbn__UseAllVocab != null;
        public void ResetUseAllVocab() => __pbn__UseAllVocab = null;
        private bool? __pbn__UseAllVocab;

        [global::ProtoBuf.ProtoMember(40, Name = @"unk_id")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int UnkId
        {
            get => __pbn__UnkId ?? 0;
            set => __pbn__UnkId = value;
        }
        public bool ShouldSerializeUnkId() => __pbn__UnkId != null;
        public void ResetUnkId() => __pbn__UnkId = null;
        private int? __pbn__UnkId;

        [global::ProtoBuf.ProtoMember(41, Name = @"bos_id")]
        [global::System.ComponentModel.DefaultValue(1)]
        public int BosId
        {
            get => __pbn__BosId ?? 1;
            set => __pbn__BosId = value;
        }
        public bool ShouldSerializeBosId() => __pbn__BosId != null;
        public void ResetBosId() => __pbn__BosId = null;
        private int? __pbn__BosId;

        [global::ProtoBuf.ProtoMember(42, Name = @"eos_id")]
        [global::System.ComponentModel.DefaultValue(2)]
        public int EosId
        {
            get => __pbn__EosId ?? 2;
            set => __pbn__EosId = value;
        }
        public bool ShouldSerializeEosId() => __pbn__EosId != null;
        public void ResetEosId() => __pbn__EosId = null;
        private int? __pbn__EosId;

        [global::ProtoBuf.ProtoMember(43, Name = @"pad_id")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int PadId
        {
            get => __pbn__PadId ?? -1;
            set => __pbn__PadId = value;
        }
        public bool ShouldSerializePadId() => __pbn__PadId != null;
        public void ResetPadId() => __pbn__PadId = null;
        private int? __pbn__PadId;

        [global::ProtoBuf.ProtoMember(45, Name = @"unk_piece")]
        [global::System.ComponentModel.DefaultValue(@"<unk>")]
        public string UnkPiece
        {
            get => __pbn__UnkPiece ?? @"<unk>";
            set => __pbn__UnkPiece = value;
        }
        public bool ShouldSerializeUnkPiece() => __pbn__UnkPiece != null;
        public void ResetUnkPiece() => __pbn__UnkPiece = null;
        private string __pbn__UnkPiece;

        [global::ProtoBuf.ProtoMember(46, Name = @"bos_piece")]
        [global::System.ComponentModel.DefaultValue(@"<s>")]
        public string BosPiece
        {
            get => __pbn__BosPiece ?? @"<s>";
            set => __pbn__BosPiece = value;
        }
        public bool ShouldSerializeBosPiece() => __pbn__BosPiece != null;
        public void ResetBosPiece() => __pbn__BosPiece = null;
        private string __pbn__BosPiece;

        [global::ProtoBuf.ProtoMember(47, Name = @"eos_piece")]
        [global::System.ComponentModel.DefaultValue(@"</s>")]
        public string EosPiece
        {
            get => __pbn__EosPiece ?? @"</s>";
            set => __pbn__EosPiece = value;
        }
        public bool ShouldSerializeEosPiece() => __pbn__EosPiece != null;
        public void ResetEosPiece() => __pbn__EosPiece = null;
        private string __pbn__EosPiece;

        [global::ProtoBuf.ProtoMember(48, Name = @"pad_piece")]
        [global::System.ComponentModel.DefaultValue(@"<pad>")]
        public string PadPiece
        {
            get => __pbn__PadPiece ?? @"<pad>";
            set => __pbn__PadPiece = value;
        }
        public bool ShouldSerializePadPiece() => __pbn__PadPiece != null;
        public void ResetPadPiece() => __pbn__PadPiece = null;
        private string __pbn__PadPiece;

        [global::ProtoBuf.ProtoMember(44, Name = @"unk_surface")]
        [global::System.ComponentModel.DefaultValue(@" ⁇ ")]
        public string UnkSurface
        {
            get => __pbn__UnkSurface ?? @" ⁇ ";
            set => __pbn__UnkSurface = value;
        }
        public bool ShouldSerializeUnkSurface() => __pbn__UnkSurface != null;
        public void ResetUnkSurface() => __pbn__UnkSurface = null;
        private string __pbn__UnkSurface;

        [global::ProtoBuf.ProtoMember(49, Name = @"train_extremely_large_corpus")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool TrainExtremelyLargeCorpus
        {
            get => __pbn__TrainExtremelyLargeCorpus ?? false;
            set => __pbn__TrainExtremelyLargeCorpus = value;
        }
        public bool ShouldSerializeTrainExtremelyLargeCorpus() => __pbn__TrainExtremelyLargeCorpus != null;
        public void ResetTrainExtremelyLargeCorpus() => __pbn__TrainExtremelyLargeCorpus = null;
        private bool? __pbn__TrainExtremelyLargeCorpus;

        [global::ProtoBuf.ProtoContract()]
        public enum ModelType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNIGRAM")]
            Unigram = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BPE")]
            Bpe = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"WORD")]
            Word = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"CHAR")]
            Char = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NormalizerSpec : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get => __pbn__Name ?? "";
            set => __pbn__Name = value;
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"precompiled_charsmap")]
        public byte[] PrecompiledCharsmap
        {
            get => __pbn__PrecompiledCharsmap;
            set => __pbn__PrecompiledCharsmap = value;
        }
        public bool ShouldSerializePrecompiledCharsmap() => __pbn__PrecompiledCharsmap != null;
        public void ResetPrecompiledCharsmap() => __pbn__PrecompiledCharsmap = null;
        private byte[] __pbn__PrecompiledCharsmap;

        [global::ProtoBuf.ProtoMember(3, Name = @"add_dummy_prefix")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool AddDummyPrefix
        {
            get => __pbn__AddDummyPrefix ?? true;
            set => __pbn__AddDummyPrefix = value;
        }
        public bool ShouldSerializeAddDummyPrefix() => __pbn__AddDummyPrefix != null;
        public void ResetAddDummyPrefix() => __pbn__AddDummyPrefix = null;
        private bool? __pbn__AddDummyPrefix;

        [global::ProtoBuf.ProtoMember(4, Name = @"remove_extra_whitespaces")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool RemoveExtraWhitespaces
        {
            get => __pbn__RemoveExtraWhitespaces ?? true;
            set => __pbn__RemoveExtraWhitespaces = value;
        }
        public bool ShouldSerializeRemoveExtraWhitespaces() => __pbn__RemoveExtraWhitespaces != null;
        public void ResetRemoveExtraWhitespaces() => __pbn__RemoveExtraWhitespaces = null;
        private bool? __pbn__RemoveExtraWhitespaces;

        [global::ProtoBuf.ProtoMember(5, Name = @"escape_whitespaces")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool EscapeWhitespaces
        {
            get => __pbn__EscapeWhitespaces ?? true;
            set => __pbn__EscapeWhitespaces = value;
        }
        public bool ShouldSerializeEscapeWhitespaces() => __pbn__EscapeWhitespaces != null;
        public void ResetEscapeWhitespaces() => __pbn__EscapeWhitespaces = null;
        private bool? __pbn__EscapeWhitespaces;

        [global::ProtoBuf.ProtoMember(6, Name = @"normalization_rule_tsv")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NormalizationRuleTsv
        {
            get => __pbn__NormalizationRuleTsv ?? "";
            set => __pbn__NormalizationRuleTsv = value;
        }
        public bool ShouldSerializeNormalizationRuleTsv() => __pbn__NormalizationRuleTsv != null;
        public void ResetNormalizationRuleTsv() => __pbn__NormalizationRuleTsv = null;
        private string __pbn__NormalizationRuleTsv;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SelfTestData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"samples")]
        public global::System.Collections.Generic.List<Sample> Samples { get; } = new global::System.Collections.Generic.List<Sample>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Sample : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"input")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Input
            {
                get => __pbn__Input ?? "";
                set => __pbn__Input = value;
            }
            public bool ShouldSerializeInput() => __pbn__Input != null;
            public void ResetInput() => __pbn__Input = null;
            private string __pbn__Input;

            [global::ProtoBuf.ProtoMember(2, Name = @"expected")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Expected
            {
                get => __pbn__Expected ?? "";
                set => __pbn__Expected = value;
            }
            public bool ShouldSerializeExpected() => __pbn__Expected != null;
            public void ResetExpected() => __pbn__Expected = null;
            private string __pbn__Expected;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ModelProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pieces")]
        public global::System.Collections.Generic.List<SentencePiece> Pieces { get; } = new global::System.Collections.Generic.List<SentencePiece>();

        [global::ProtoBuf.ProtoMember(2, Name = @"trainer_spec")]
        public TrainerSpec TrainerSpec { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"normalizer_spec")]
        public NormalizerSpec NormalizerSpec { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"self_test_data")]
        public SelfTestData SelfTestData { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"denormalizer_spec")]
        public NormalizerSpec DenormalizerSpec { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class SentencePiece : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"piece")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Piece
            {
                get => __pbn__Piece ?? "";
                set => __pbn__Piece = value;
            }
            public bool ShouldSerializePiece() => __pbn__Piece != null;
            public void ResetPiece() => __pbn__Piece = null;
            private string __pbn__Piece;

            [global::ProtoBuf.ProtoMember(2, Name = @"score")]
            public float Score
            {
                get => __pbn__Score.GetValueOrDefault();
                set => __pbn__Score = value;
            }
            public bool ShouldSerializeScore() => __pbn__Score != null;
            public void ResetScore() => __pbn__Score = null;
            private float? __pbn__Score;

            [global::ProtoBuf.ProtoMember(3)]
            [global::System.ComponentModel.DefaultValue(Type.Normal)]
            public Type type
            {
                get => __pbn__type ?? Type.Normal;
                set => __pbn__type = value;
            }
            public bool ShouldSerializetype() => __pbn__type != null;
            public void Resettype() => __pbn__type = null;
            private Type? __pbn__type;

            [global::ProtoBuf.ProtoContract()]
            public enum Type
            {
                [global::ProtoBuf.ProtoEnum(Name = @"NORMAL")]
                Normal = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
                Unknown = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"CONTROL")]
                Control = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"USER_DEFINED")]
                UserDefined = 4,
                [global::ProtoBuf.ProtoEnum(Name = @"BYTE")]
                Byte = 6,
                [global::ProtoBuf.ProtoEnum(Name = @"UNUSED")]
                Unused = 5,
            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
